print("HOW MANY ITEMS WOULD YOU LIKE TO BUY")
itemamount = (input())
itemtotal = int(itemamount)
print("WHAT ITEM IS IT")
itemtype = (input())
print("PRICE PER ITEM")
itemprice = (input())
itemprices = int(itemprice)
itemextended = int(itemprices * itemtotal)
itemabsolute = int(itemextended * 0.15)
item = int(itemextended + itemabsolute)
item1 = str(itemextended)
item2 = str(itemabsolute)
item3 = str(item)
print("SUBTOTAL: ")
print(item1)
print("TIP: ")
print(item2)
print("TOTAL: ")
print(item3)